version: '3.9'

services:
  nuxt:
    container_name: nuxt
    build: ./frontend
    volumes:
      - ./frontend:/code
    ports:
      - "80:3000"
    environment:
      - APP_BASEURL=${APP_BASEURL}
      - MICROCMS_SERVICE_DOMAIN=${MICROCMS_SERVICE_DOMAIN}
      - MICROCMS_API_KEY=${MICROCMS_API_KEY}
    command: >
      bash -c "rm -rf /tmp/nitro/worker-* &&
      yarn &&
      yarn generate &&
      npx serve .output/public"
