version: '3.9'

services:
  nuxt:
    container_name: nuxt
    build: ./frontend
    volumes:
      - ./frontend:/code
    ports:
      - "80:3000"
      - "24678:3000"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - APP_BASEURL=${APP_BASEURL}
      - MICROCMS_SERVICE_DOMAIN=${MICROCMS_SERVICE_DOMAIN}
      - MICROCMS_API_KEY=${MICROCMS_API_KEY}
    command: |
      rm -rf /tmp/nitro/worker-* &&
      yarn dev
