name: Deploy

on: workflow_dispatch

env:
  APP_BASEURL: /constantan
  APP_CDNURL: /constantan/.output/public

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install modules
      run: |
        cd frontend
        yarn install
    - name: Generate output
      id: generate_output
      run: |
        cd frontend
        npx nuxt generate
    - name: Upload artifacts
      id: upload_artifacts
      if: steps.generate_output.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: frontend/.output
    - name: Fire webhook
      if: steps.upload_artifacts.outcome == 'success'
      run: curl -X POST -d 'secret-key=${{ secrets.SECRET_KEY }}' https://home.hiroshima-u.ac.jp/constantan/webhook.cgi
