name: Deploy

on: workflow_dispatch

env:
  APP_BASEURL: /constantan
  APP_CDNURL: /constantan/.output/public
  MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
  MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Modules
      run: |
        cd frontend
        yarn install
    - name: Generate Output
      id: generate_output
      run: |
        cd frontend
        npx nuxt generate
    - name: Upload Artifacts
      if: steps.generate_output.outcome == 'success'
      id: upload_artifacts
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: frontend/.output
    - name: Fire Webhook
      if: steps.upload_artifacts.outcome == 'success'
      run: curl -X POST -d 'secret-key=${{ secrets.SECRET_KEY }}' https://home.hiroshima-u.ac.jp/constantan/webhook.cgi
